version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - revive
    - misspell

formatters:
  enable:
    - gofmt

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true

run:
  timeout: 5m
  tests: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
