apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llmrouter.fullname" . }}
  labels:
    {{- include "llmrouter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "llmrouter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "llmrouter.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          env:
            - name: CONFIG_SOURCE
              value: {{ .Values.config.source | quote }}
            {{- if eq .Values.config.source "remote" }}
            - name: CONFIG_URL
              value: "http://{{ include "llmrouter.fullname" . }}-config-server:8081/v1/sync"
            {{- else }}
            - name: CONFIG_PATH
              value: "/etc/llmrouter/config.yaml"
            {{- end }}
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "llmrouter.fullname" . }}-secrets
                  key: GROQ_API_KEY
          {{- if eq .Values.config.source "file" }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/llmrouter
          {{- end }}
      {{- if eq .Values.config.source "file" }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "llmrouter.configMapName" . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
