apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llmrouter.fullname" . }}-secrets
  labels:
    {{- include "llmrouter.labels" . | nindent 4 }}
type: Opaque
stringData:
  GROQ_API_KEY: {{ .Values.secrets.groqApiKey | quote }}
